/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as PostRouteImport } from './routes/post'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as GigIdRouteImport } from './routes/gig.$id'
import { Route as UUidRouteImport } from './routes/u.$uid'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PostRoute = PostRouteImport.update({
  id: '/post',
  path: '/post',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const GigIdRoute = GigIdRouteImport.update({
  id: '/gig/$id',
  path: '/gig/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const UUidRoute = UUidRouteImport.update({
  id: '/u/$uid',
  path: '/u/$uid',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bookings': typeof BookingsRoute
  '/dashboard': typeof DashboardRoute
  '/post': typeof PostRoute
  '/profile': typeof ProfileRoute
  '/gig/$id': typeof GigIdRoute
  '/u/$uid': typeof UUidRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bookings': typeof BookingsRoute
  '/dashboard': typeof DashboardRoute
  '/post': typeof PostRoute
  '/profile': typeof ProfileRoute
  '/gig/$id': typeof GigIdRoute
  '/u/$uid': typeof UUidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bookings': typeof BookingsRoute
  '/dashboard': typeof DashboardRoute
  '/post': typeof PostRoute
  '/profile': typeof ProfileRoute
  '/gig/$id': typeof GigIdRoute
  '/u/$uid': typeof UUidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/bookings'
    | '/dashboard'
    | '/post'
    | '/profile'
    | '/gig/$id'
    | '/u/$uid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/bookings'
    | '/dashboard'
    | '/post'
    | '/profile'
    | '/gig/$id'
    | '/u/$uid'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/bookings'
    | '/dashboard'
    | '/post'
    | '/profile'
    | '/gig/$id'
    | '/u/$uid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BookingsRoute: typeof BookingsRoute
  DashboardRoute: typeof DashboardRoute
  PostRoute: typeof PostRoute
  ProfileRoute: typeof ProfileRoute
  GigIdRoute: typeof GigIdRoute
  UUidRoute: typeof UUidRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post': {
      id: '/post'
      path: '/post'
      fullPath: '/post'
      preLoaderRoute: typeof PostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gig/$id': {
      id: '/gig/$id'
      path: '/gig/$id'
      fullPath: '/gig/$id'
      preLoaderRoute: typeof GigIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$uid': {
      id: '/u/$uid'
      path: '/u/$uid'
      fullPath: '/u/$uid'
      preLoaderRoute: typeof UUidRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BookingsRoute: BookingsRoute,
  DashboardRoute: DashboardRoute,
  PostRoute: PostRoute,
  ProfileRoute: ProfileRoute,
  GigIdRoute: GigIdRoute,
  UUidRoute: UUidRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
